<table class="table align-middle table-striped table-hover table-sm">
  <thead>
    <tr>
      <th>ESCUELA</th>
      <th>NOMBRES</th>
      <th>DOCUMENTO</th>
      <th>CARRERA</th>
      <th>ACTA</th>
      <th>REGISTRO</th>
      <th>FOLIO</th>
      <th>LIBRO</th>
      <th>SNIES</th>
      <th>DIA_TEXTO</th>
      <th>DIA_NUMERO</th>
      <th>MES_TEXTO</th>
      <th>AÑO_NUMERO</th>
      <th>FECHA_GRADO</th>
      <th>DADO_EN</th>
      <th>GENERO</th>
      <th>AÑO_TEXTO</th>
      <th>TIPO_DOCUMENTO</th>
      <th>OBSERVACIONES</th>
      <th>DONDE_RECIBE</th>
      <th>FECHA</th>
      <th>HORA</th>
      <th>CICLO</th>
      <th>CEREMONIA</th>
      <th>CORREO</th>
      <th>LUGAR</th>
      <th>PROGRAMA</th>
      <th>CICLO_NUMERO</th>
      <th>PROMEDIO</th>
      <th>SILLA</th>
    </tr>
  </thead>
  <tbody>
    @foreach ($allData as $item)
      <tr>
        <td>{{$item->ESCUELA}}</td>
        <td>{{$item->NOMBRES}}</td>
        <td>{{$item->CODIGO_UNICO}}</td>
        <td>{{$item->CARRERA_TITULO}}</td>
        <td>{{$item->ACTA}}</td>
        <td>{{$item->REGISTRO}}</td>
        <td>{{$item->FOLIO}}</td>
        <td>{{$item->LIBRO}}</td>
        <td>{{$item->SNIES}}</td>
        <td>{{$item->DIA_TEXTO}}</td>
        <td>{{$item->DIA_NUMERO}}</td>
        <td>{{$item->MES_TEXTO}}</td>
        <td>{{$item->AÑO_NUMERO}}</td>
        <td>{{$item->FECHA_GRADO}}</td>
        <td>{{$item->DADO_EN}}</td>
        <td>{{$item->GENERO}}</td>
        <td>{{$item->AÑO_TEXTO}}</td>
        <td>{{$item->TIPO_DOCUMENTO}}</td>
        <td>{{$item->OBSERVACIONES}}</td>
        <td>{{$item->DONDE_RECIBE}}</td>
        <td>{{$item->FECHA}}</td>
        <td>{{$item->HORA}}</td>
        <td>{{$item->CICLO}}</td>
        <td>{{$item->CEREMONIA}}</td>
        <td>{{$item->CORREO}}</td>
        <td>{{$item->LUGAR}}</td>
        <td>{{$item->PROGRAMA}}</td>
        <td>{{$item->CICLO_NUMERO}}</td>
        <td>{{$item->PROMEDIO}}</td>
        <td>{{$item->SILLA}}</td>
      </tr>
    @endforeach
  </tbody>
</table>
